In [2]:
import numpy as np


In [9]:
# arrays
s = np.array(5)
x = s + 3
print(s.shape, x, type(x))


8 <class 'numpy.int64'>


In [12]:
# vectors
v = np.array([1,2,3])
print(v.shape)

x = v[1]
print(x)

print(v[1:])

(3,)
2
[2 3]


In [14]:
# matrices
m = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(m.shape)
print(m[1][2])

(3, 3)
6


In [16]:
# Tensors
t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],[[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[17]]]])
print(t.shape)
print(t[2][1][1][0])

(3, 3, 2, 1)
16


In [17]:
# reshaping
v2 = np.array([1,2,3,4])
print(v2.shape)
x2 = v2.reshape(1,4)
print(x2.shape)

(4,)
(1, 4)


In [20]:
# reshaping using slicing
print(v2.shape)

x3 = v2[None, :]
print(x3.shape)

x4 = v2[:, None]
print(x4.shape)

(4,)
(1, 4)
(4, 1)


In [7]:
# scalar + matrix math
# python way
values = [1,2,3,4,5]
for i in range(len(values)):
    values[i] += 5
print(values)

# numpy way
values = [1,2,3,4,5]
values = np.array(values) + 5
print(values)

values += 5
print(values)

x = np.multiply(values, 5)
x = values * 5
print(x)

# set to zero to reuse
x *= 0
print(x)


[6, 7, 8, 9, 10]
[ 6  7  8  9 10]
[11 12 13 14 15]
[55 60 65 70 75]
[0 0 0 0 0]


In [11]:
# matrix and matrix manipulations
a = np.array([[1,3],[5,7]])
b = np.array([[2,4],[6,8]])
print(a)
print(b)
print(a+b)

# unequal matrices
c = np.array([[2,3,6],[4,5,9],[1,8,7]])
print(a * c)

[[1 3]
 [5 7]]
[[2 4]
 [6 8]]
[[ 3  7]
 [11 15]]


ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 

In [13]:
# matrix multiply
print(a*b)
print(np.multiply(a, b))


[[ 2 12]
 [30 56]]
[[ 2 12]
 [30 56]]


In [14]:
# matrix product
np.matmul(a, b)


array([[20, 28],
       [52, 76]])

In [15]:
# dot - only same if matrices are 2D
np.dot(a, b)

array([[20, 28],
       [52, 76]])

In [18]:
# transpose of a matrix
m = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(m)
m.T

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [ ]:
np.min